src/pci_virtio_sock.c

These changes take the latency of a simple ping test (small request sent from the host Unix domain socket to a vsock echo server in the guest, 500,000 times) from having a 50<sup>th</sup> percentile of 80-90µs and a 90<sup>th</sup> of ~110-140µs (with a lot of jitter across different runs) to a 50<sup>th</sup> of 40-50µs and a 90<sup>th</sup> of ~75µs (and with considerably less jitter). The overall throughput for large request remains around 140-150MiB/s, although there is an initial drop (to ~120MiB/s) with the initial switch to using the lists this is regained by the later changes (primarily amortizing the rx kick it seems).

vsock latency improvements

---

src/pci_virtio_sock.c

even if they don't need to be polled. Otherwise a socket which e.g. has
"local_shutdown & SHUTDOWN_TX" won't ever send a credit update and so guest TX
will stall.
Plus a fixup to debug mode.

vsock: Add socks which require a credit update to the rx_queue

---

Makefile
src/pci_virtio_net_vpnkit.c

When this was developed vpnkit didn't yet have a name, now that it does rename
it to fit and add the frontend protocol inline instead of expecting it
externally (and simplify things along the way).

Rename/port net_ipc virtio backend to net_vpnkit

---

src/block_if.c
src/pci_virtio_9p.c
src/pci_virtio_net_tap.c
src/pci_virtio_net_vmnet.c
src/pci_virtio_net_vpnkit.c
src/vmm/vmm_callout.c
src/xhyve.c

Only appears to be supported by lldb and "Saved crash reports" today but not
gdb or instruments.

Name each pthread as an aid to debugging.

---

src/pci_virtio_sock.c

Follows on from "Name each pthread as an aid to debugging." in master (PR #30).

Name vsock threads.

---

Makefile
TESTING.md
circle.yml
test_linux.exp

Fixes #24
Adds dependency on expect, wired in through Makefile.
The expect script replicates the command from hyperkitrun.sh to prevent
requiring a prompt whilst in expect. The dependecy chain is handled in
the Makefile.
Tested both success and failure using make test - adjusting the timeout
to 1 will give an example fail that propgates up to the make return.
Signed-off-by: Pris Nasrat <pnasrat@gmail.com>

Introduce simple boot cycle test for hyperkit.

---

test/tinycore.sh

Optimized the tinycore.sh script:
- Rearranged errexit parameter for sh
- Replace```gzcat``` with ```gzip -dc``` for a better [portability](c9s/perlomni.vim#16)
- Create a temporary directory and do the work within this directory. Easy way to clean up

Minor optimization of tinycore.sh script

---

.gitignore
Makefile
README.md
config.mk
dtrace/eptfault.d
dtrace/vmxexit.d
src/block_if.c
src/dtrace.d
src/vmm/intel/vmx.c

This pull request adds all the build system bits needed to support static DTrace trace points and defines one sample trace point as an example.
DTrace provides a great ability to dig inside a running system with little to none overhead and will be of great help during performance investigations.
Example usage is shown in the second commit message.

Introduce support for Dtrace static trace points

---

include/xhyve/support/misc.h
include/xhyve/vmm/io/vlapic_priv.h
src/vmm/io/vatpic.c
src/vmm/io/vatpit.c
src/vmm/io/vioapic.c
src/vmm/io/vlapic.c
src/vmm/vmm.c

@RnbWd reported in #47 and #48 that OSSpinLock is deprecated in OSX 10.12 (Sierra, beta 3). Rather than switch to a different lock only for 10.12+ (as was done in #48) this PR instead switches everything over to use pthread mutexes which are available on all versions.
I'm not completely wedded to the `xpthread_mutex_foo` wrappers to do error checking (names by analogy to the more commonly used `xmalloc` wrappers), but I think we certainly need to check at least that `pthread_mutex_lock` actually locked something even though the errors are in the "should never happen category".

Switch all OSSpinLock uses to pthread_mutex_t

---

test/tinycore.sh

make test was failing due to the mktemp variation in osx 10.10.5

fixed make test failure in osx 10.10.5 - see https://github.com/docker/hyperkit/issues/52

---

src/pci_virtio_sock.c

V7 spec was posted to the virtio-spec list in <1470324277-19300-1-git-send-email-stefanha@redhat.com>.
This requires a corresponding update to the Linux frontend to the v6 RFC patches posted as <1469716595-13591-1-git-send-email-stefanha@redhat.com>. These have also been merged into Linux v4.8-rc1.
This should hopefully fix docker/hyperkit#50.

Update virt-sock backend to v7 spec

---

circle.yml
src/block_if.c
src/mirage_block_c.c
src/mirage_block_c.h
src/mirage_block_ocaml.ml

The mirage-block-unix has a revamped disk configuration interface where a `Block.Config.t` represents a desired configuration including parameters
- whether using buffered I/O or not
- whether honouring `flush` or not (possibly more options here in future)
- the path to the file
This patch simplifies the mirage block interface by using `Block.Config.of_string` rather than manually parsing a URI here. The device can then be opened with `Block.of_config`. In future if mirage-block-unix gains some extra parameters, this code won't have to be modified (hopefully)
Note this new interface is not yet in a released version, so this PR includes an extra `opam pin` in the `circle.yml`.
This is part of a workaround for [docker/for-mac#668]

Open block devices using the `Block.Config` interface

---

README.md
circle.yml

- remove the pin for `mirage-block-unix` (not needed any more and actually harmful as the master branch has incompatible interfaces)
- add a note to the README to explain that an existing pin to `mirage-block-unix` should be removed
- removed an out-of-date note in the README about the `sexplib` library
/cc @yomimono @ijc25 @rneugeba

Remove mirage-block-unix pin

---

include/xhyve/firmware/kexec.h
src/firmware/kexec.c

Fix `ramdisk_start` promlem in the [kexec.c](https://github.com/docker/hyperkit/blob/master/src/firmware/kexec.c).
- Use the `initrd_addr_max` value from the kernel header if the kernel version is 2.03 or newer.
- ref: https://github.com/zchee/linux-documentation/blob/master/x86/boot.md#initrd_addr_max
- Use hardcoded(`0x37ffffff`) value if older.
- Compare the `initrd_max` and `memory.size`, and re-assign if `initrd_max` is larger.
- Add `ALIGNDOWN` macro for `ramdisk_start`, uses prevent to go past the address limit.
- Fix typo for `initrd_addr_max`. thanks @dlorenc
Based on [qemu/hw/i386/pc.c](https://github.com/qemu/qemu/blob/master/hw/i386/pc.c#L954-L979).
Close https://github.com/docker/hyperkit/issues/63

kexec: fix wrong calculation method of ramdisk_start

---

src/lib/firmware/kexec.c

Various bits of code (e.g. kernel and initrd loading) rely on memory.base and
memory.size referring to lowmem only, with highmem being handled separately, in
order to avoid locating things into the MMIO region between the two.
Rename the variable to make this more obvious and to forestall any ideas about
"fixing" memory.size.
/cc @zchee I think this would have saved us a few RTTs on #66!
/cc @rneugeba I'll hold off on this until after #65 and rebase accordingly once you have merged.

kexec: Rename "memory" to "lowmem".

---

Makefile
README.md
circle.yml

[Lwt](https://github.com/ocsigen/lwt) [optionally depends on libev](https://github.com/ocsigen/lwt/blob/d638502667005270cb69bad282f89afa9370838e/opam#L43).  This PR updates the Makefile to statically link in `libev` if it's available.

Link in libev, which is sometimes needed for Lwt.

---

src/hyperkit.c
src/include/xhyve/vmm/vmm.h
src/include/xhyve/vmm/vmm_api.h
src/lib/vmm/intel/vmx.c
src/lib/vmm/vmm.c
src/lib/vmm/vmm_api.c

Otherwise if we take a trap for e.g. VM_EXITCODE_VMX then we have very little
to go on (basically only RIP and exit_reason + qualification).
Plumb the existing hvdump function (which dumps a lot of useful VMCS state,
including guest register state) up through the various API layers and have the
top-level call it for any VMEXIT_ABORT.
/cc @rneugeba you might have opinions on the API layering and how to expose things?
Tested by adding an artificial VMEXIT_ABORT to `vcpu_loop` after 100 exits since I don't currently have an easy way to force such an exit.

Dump VM state on VMEXIT_ABORT

---

hyperkit.1
src/lib/block_if.c
test/test_linux.exp

I haven't checked, whether all kinds of volumes work, but virtual disk images do, which allows you to use sparse volumes now with xhyve.
Example:
```
hdiutil create -megabytes 20 -fs "MS-DOS" disk
hdiutil attach disk.dmg // Get disk number
xhyve ... -s 4:0,ahci-hd,/dev/rdiskN ...
```
Ported from https://github.com/mist64/xhyve/pull/80

Partial support for raw devices

---

circle.yml

First build and test (which assumes that ocaml is not present in the base
circle image) then install opam etc and do it again with ocaml enabled.

circle.yml: Build and test with and without ocaml

---

README.md
circle.yml
src/lib/block_if.c
src/lib/dtrace.d
src/lib/mirage_block_c.c
src/lib/mirage_block_c.h
src/lib/mirage_block_ocaml.ml

This PR adds support for `delete` (aka `discard` or `TRIM`) via the Mirage Qcow library.
The capability `candelete` (used to set `ATA_SUPPORT_RZAT | ATA_SUPPORT_DRAT` in `src/lib/pci_ahci.c`) is returned from an expanded `mirage_block_stat` call, while the `delete` operation itself is plumbed through a new function `mirage_block_delete`.
Since the Mirage Qcow library supports multiple configuration options (and more are going to be added over time), an extra configuration string is plumbed through via the new block parameter `qcow-config=`.
Related to [docker/for-mac#371]

Add support for qcow delete/discard/TRIM

---

dtrace/eptfault.d
dtrace/vmxexit.d

This patchset adds rate counting modes (default, accumulator mode with `-DTOTAL`) to the `vmxexit.d` and `eptfault.d` dtrace scripts and a LAPIC register decoder to `eptfault.d`. These changes make steady-state performance comparison and EPT fault analysis easier.
Sorry about the repo branch. I'll make a fork for next time.

dtrace script improvements

---

src/lib/pci_virtio_sock.c

When buffering due to a partially successful write we need to add the
successful part of the write to fwd_cnt otherwise we miss those bytes in our
accounting and will eventually fall behind enough that we think we cannot
forward any more traffic.
With this in place the mysql test case in https://github.com/docker/for-mac/issues/825 now succeeds for me.

vsock: correctly account partial writes on tx

---

src/lib/vmm/vmm_api.c

This is related to FreeBSD-SA-16:38.bhyve[0] AKA CVE-2016-1889 which was
discovered by Felix Wilhelm. In the context of hyperkit the code in question
runs as an unprivileged user.
Thanks to Gleb Smirnoff and the FreeBSD security team for advanced notice on
this issue.
[0] https://lists.freebsd.org/pipermail/freebsd-announce/2016-December/001773.html

Avoid integer overflow in xh_vm_map_gpa()

---

Makefile
README.md
circle.yml
src/lib/mirage_block_ocaml.ml

Previously the qcow library could emit errors and warnings but these would be dropped since the logging system wasn't initialised. This patch should cause these messages to be printed to stderr, along with the other output from hyperkit.

ocaml: initialise the logging system used by the qcow library

---

src/lib/pci_virtio_sock.c

Signed-off-by: Jeremy Yallop <yallop@docker.com>

Add a missing '='.

---

src/lib/mirage_block_c.c
src/lib/mirage_block_c.h
src/lib/mirage_block_ocaml.ml

This patch fixes a segfault triggered by setting `format=qcow` but not providing a `qcow-config` parameter. The Mirage qcow interface already treats this configuration as an optional value. This patch modifies the C -> OCaml interface to map NULL onto None.
Fixes #88

ocaml: qcow-config should be optional

---

.gitignore
Makefile
circle.yml
test/test_linux_qcow.exp

- verify that we can boot up a VM with a .qcow2-backed block device and successfully write to it
- check that the without-qcow build really is without-qcow: this will fail if the CI base image were ever to have the qcow dependencies installed in it
Tests #88

Add some qcow-related tests

---

README.md
circle.yml
src/lib/mirage_block_ocaml.ml

Modern versions of `qcow` when configured to automatically compact will wait until there have been no `discard`s for some period of time in order to batch a run of `discard`s together.

ocaml: qcow >= 0.7.0 is functorised over Time

---

src/include/xhyve/vmm/vmm_common.h
src/lib/acpitbl.c

Increase the MADT size accordingly. Add a compile time
check to make sure the MADT doesn't overflow into the FADT.
resolves #96

Increase the maximum number of vCPUs to 64

---

src/lib/vmm/intel/vmx.c

These may or may not be valid for a particular fault but other
information which is already logged (such as the vmexit qualification)
should allow a developer to work out if the values are valid on a case
by case basis.

Dump guest physical and linear address from VMCS when dumping state

---

Makefile
README.md
circle.yml
src/lib/mirage_block_ocaml.ml

This PR updates to the new Mirage v3 block API and includes the latest version of the `qcow` library which supports flushing via `fsync` as well as `fcntl`: see [docker/for-mac#668]
Note the Mirage 3 packages have been tagged and released but the package metadata is in a new repository: https://github.com/mirage/mirageos-3-beta. This PR updates the `circle.yml` and the instructions in the `README.md` accordingly.

Update to Mirage 3

---

README.md
circle.yml

This code has all been released upstream and the repo has been removed.

ocaml: remove the mirageos-3-beta repo

---

Makefile
README.md
circle.yml
dtrace/eptfault.d
dtrace/vmxexit.d
hyperkitrun.sh
test/test_linux.exp
test/test_linux_qcow.exp

The name `hyperkit`
- is a more conventional format name
- matches the name of the github repo
- is shorter and easier to type
- is consistent with vpnkit (repo = vpnkit; binary = vpnkit)

Rename com.docker.hyperkit to hyperkit

---

Makefile

This patch adds the missing stubs to the link invocation.

ocaml: add stubs from `base`, new dependency of `sexplib`

---

go/hyperkit.go

This is used in most recent Docker for Mac.
Signed-off-by: Justin Cormack <justin.cormack@docker.com>

Add another default hyperkit path

---

hyperkit.1
src/hyperkit.c
src/lib/acpitbl.c
src/lib/firmware/bootrom.c
src/lib/firmware/fbsd.c
src/lib/mevent.c

- Use 0 for both poweroff and halt. They are more or less the same.
- Use 2 when the guest rebooted. This allows the user to restart
the process, possibly with some changes, such as removing a
CDROM device.
The other exit codes are untouched.
Also document the exit codes in the man page while at it.
resolves #108

Change the exit codes to something saner

---

src/hyperkit.c
src/include/xhyve/xhyve.h
src/lib/pci_virtio_net_vmnet.c

This global option was specific to one network backend,
irrespective of it being configured via -s.
It is also uncertain that a VM will get a the same MAC
address on a second invocation, so the usefulness of the
option is questionable.

Remove "-M"/"print_mac" option.

---

src/hyperkit.c

Missed this in the previous commit.

Also remove the -M option from the help message

---

go/hyperkit.go
go/sample/main.go

- optionally enable the virtio-socket device (resolves #109)
- add a option to sample code to enable the virtio-socket device
- allow the hyperkit package to be used on non-macOS systems (to make it easier for downstream users to consume)

Some improvements to the go bindings

---

go/hyperkit.go

The three Errorf lines where called out by one downstream project.
Some versions of lint seem pickier than others ...

go: Fix some lint complains

---

go/hyperkit.go

The UUID allows a VM to get more consistent network settings.

go: Expose the VPNKit UUID via the go binding

---

go/hyperkit.go

We have missused UUID filed for VPNKit, and not the `-U` flag which it naturally maps to.
It seems reasonably to leave it up to the caller how they wish to generate UUIDs.
This is a breaking change, hence I marked it WIP (so it doesn't gets merged too soon), and the biggest question question is how should we communicate this change to those who depend on these bindings?

[WIP] Change meaning of UUID field, add VPNKitKey field

---

README.md
circle.yml
test/test_linux_qcow.exp

- add a simple file copy benchmark
- add bindings for readv, writev
- cache the file offset and avoid unnecessary calls to lseek
- CLI: `check` and `sha` will nolonger resize the file as a side-effect
(#84)
- Allow the number of `cluster_bits` to be set in `create`
- Strictly enforce the cluster move state machine
- Don't start moving new blocks while existing moves are in progress
(fix bug where the same destination block could be reused)
- Hold a lock to exclude `flush` while updating references to ensure
reference updates hit the disk before the move is considered complete
- Simplify allocator by always adding blocks to the Roots set before
returning. The caller must transfer them somewhere else.
- Simplify the cluster moving API by combining `get_moves` with
`start_moves`, so it's not …

Update to latest qcow and mirage-block-unix

---

circle.yml

Projects using Hyperkit need its license. This is the code that generate it in Docker for Mac project. 
I propose to reuse it here, or perhaps we should use a simple LICENSE file at root of the repository ?

Generate LICENSE file

---

circle.yml

Circleci binary was not compatible with macOS 10.10. In Docker for Mac, we need to support this version (at least for some weeks).

Circleci artifacts work on macOS 10.10

---

Makefile
hyperkit.1
src/hyperkit.c
src/include/xhyve/firmware/multiboot.h
src/lib/firmware/multiboot.c

Hi.
This patch set addresses issue #38 and implements multiboot. It is based on work done by @joshado in https://github.com/joshado/xhyve/tree/multiboot
The first patch is an as-is copy of the code from @joshado's repo (I hope he doesn't mind that I've added his Signed-off-by). The next patches address some coding style and do some refactoring.
The last patch implements some minimal support for ELF images.
Currently, only kernel image itself is loaded. Modules are not yet loaded and command line is not yet passed to the kernel.
With these patches applied I am able to successfully boot @joshado's multiboot test (not yet included in the pull request, as some test framework refactoring is required for this) and binaries from kvm-unit-tests package …

Initial implementation of multiboot

---

src/lib/pci_virtio_net_vpnkit.c

Previously we would fail if the remote server didn't report a version of exactly 1. In practice this protocol has evolved only by extension, with new command types being added. All known versions support the "ethernet" command that we need.
This patch removes the strict check of the remote vpnkit protocol version. This allows `hyperkit` to connect to the `com.docker.vmnetd` daemon which comes with Docker for Mac (as well as `vpnkit`)

virtio-vpnkit: remove the strict remote version check

---

go/hyperkit.go
go/sample/main.go

- Add VSockPorts and VSockGuestCID to HyperKit struct. Guest CID is 3 by
default.
- Add comma separated list of forwarded ports as -vsock-ports cli parameter in sample.
Signed-off-by: Magnus Skjegstad <magnus@skjegstad.com>

Add support for specifying CID and guest ports to forward in go code

---

Makefile
README.md
circle.yml
src/lib/block_if.c
src/lib/mirage_block_c.c
src/lib/mirage_block_c.h
src/lib/mirage_block_ocaml.ml

The qcow library gathers a set of metrics in prometheus format including
- read, write, discard rate
- bytes used, file size
- bytes erased, deallocated and in various GC states
It's useful to be able to expose these for monitoring, see for example the Grafana dashboard here:
https://github.com/mirage/ocaml-qcow/issues/99
This patch adds an optional `qcow-stats-config=` argument which supports values
- `unix:/path/to/socket` -- listen on a Unix domain socket
- `tcp:port` -- listen on `0.0.0.0:port`
(unfortunately the Mirage `conduit` library doesn't allow the bind address to be customised, so care must be taken with the `tcp:` option)
By default nothing is exposed.

qcow: add an optional qcow-stats-config= argument

---

go/hyperkit.go
go/sample/main.go

Add support for specifying the path and tag of 9p unix domain sockets
that will be exposed to the guest. This is needed to e.g. expose the
vpnkit /ports directory in the guest.
Also adds a nextSlot counter when building the command line so it's
easier to add new parameters that could require multiple PCI slots.
The sample only supports a single 9p socket for now.
Signed-off-by: Magnus Skjegstad <magnus@skjegstad.com>

go lib: Add support for 9p sockets

---

go/hyperkit.go

path.Clean() will set the VPNKit socket path to "." if the input string
is empty. As the HyperKit API uses an empty socket path to disable
networking this made it impossible to disable network support.
The empty socket path is documented in the code here:
https://github.com/moby/hyperkit/blob/master/go/hyperkit.go#L131
Signed-off-by: Magnus Skjegstad <magnus@skjegstad.com>

Always return empty VPNKit socket path when input is empty

---

go/Makefile

While the hyperkit go package is only useful on macOS, consumers
may want to use it in code which also also needs compiling on Windows
and Linux without having to use OS conditional compilation.
This patch adds checks to the CI to ensure the code cross compiles
on other platforms.

go: Add cross-compile tests for Linux and Windows

---

go/hyperkit.go

Also have matching patch for `linuxkit run` to enable it.
This allows people who want routable IP addresses on LinuxKit
to use vmnet (with all its downsides).
Signed-off-by: Justin Cormack <justin.cormack@docker.com>

Add vmnet networking support to Go API

---

Makefile

As a result of the recent `io-page` refactor which split the package into 3 to remove the optional dependency and simplify the build rules more generally[1], the stubs are now in the directory `io-page-unix`.
This should fix the CircleCI build.
[1] https://discuss.ocaml.org/t/ann-io-page-2-0-0-with-packaging-changes/440

ocaml: the io_page_unix stubs are in a different directory

---

src/include/xhyve/virtio.h

According to the virtio spec[1] the device ID for the virtio
entropy source is 0x1005 and not 0x1002. This fix was already applied
to bhyve[2]. Linux and FreeBSD guests typically match on the
device type and ignore the device ID.
[1] http://docs.oasis-open.org/virtio/virtio/v1.0/cs04/virtio-v1.0-cs04.html#x1-6600011
[2] https://github.com/freebsd/freebsd/commit/919dec09c25924259b40d9f6d09a52ac00bbbba2

virtio: Fix device ID for the virtio random device

---

go/hyperkit.go

This PR adds simple support for pre-configured disks of different types. Specifically, I'd like to be able to use the go wrapper to create VMs with attached qcow2 and sparsebundle disk types.
Apologies in advance for sending this PR without discussion on an issue first. I'm more than happy to refactor this or approach it in some other way.
Signed-off-by: dlorenc <lorenc.d@gmail.com>

Add Go wrapper support for different disk formats and drivers.

---

Makefile
README.md
circle.yml

`brew` now has OCaml 4.05 which is incompatible with some of the older dependencies. This patch bumps the versions of some of the dependencies and updates the linking step to match.
As a special bonus this removes some libraries which were being linked by accident and shrinks the binary size from:
```
$ ls -l build/hyperkit
-rwxr-xr-x  1 djs  staff  7356796  3 Aug 17:25 build/hyperkit
```
to
```
$ ls -l build/hyperkit
-rwxr-xr-x  1 djs  staff  3965068  3 Aug 17:00 build/hyperkit 
```

ocaml: update packages to fix CI with OCaml 4.05

---

go/hyperkit.go
go/sample/main.go

Needed if you boot off an ISO and also want to use one for metadata....
Signed-off-by: Justin Cormack <justin.cormack@docker.com>

Allow any number of ISO images to be attached in Go API

---

go/hyperkit.go
go/sample/main.go
src/lib/pci_virtio_net_vpnkit.c

This updates the VPNKit protocol to version 22. This change is incompatible with earlier versions of VPNKit and depends on moby/vpnkit#277.
It was previously possible to encode an IP address in the UUID to request a fixed address from VPNKit. This replaces this functionality with a `preferred_ipv4=` option that can be passed to the driver. IPs encoded in UUIDs are now ignored and treated as a regular UUID.
The new server error messages allows the driver to inform the user about some common VPNKit error conditions, such as if the IP is unavailable. The old driver would just fail with an unspecified vif error.

VPNKit protocol and Go API update

---

go/hyperkit.go

Previously we made a disk be the correct size by explicitly writing zeroes to it.
This patch uses `Truncate` to make the disk the correct size. If the filesystem supports sparse files (e.g. APFS) then
- it's very fast
- it doesn't actually allocate any space until the VM writes to it

go: create disks with Truncate

---

circle.yml
test/tinycore.sh

This includes a more recent version of clang.

circleci: upgrade xcode from 7.3 to 9.0

---

src/lib/block_if.c
src/lib/pci_ahci.c

The macOS API `fcntl(F_PUNCHHOLE)` will successfully punch holes in files on APFS and free the backing storage so we can use this to implement the host side of TRIM.
The arguments to the `fcntl` need to be aligned to the filesystems `f_bsize` as returned by `statfs` (which on my Mac's SSD is 4096).
Unfortunately exposing the 4096 byte sectors to the guest seems to trigger a bug elsewhere in the ACHI implementation so this patch maintains a virtual sector size of 512 bytes. This means that the guest will send 512 byte-aligned requests, we must round these to (eg) 4096 byte-aligned requests and manually zero any leading and trailing sectors. For the zeroing we allocate a `delete_zero_buf` per block device and pre-zero it.
When the device is opened we perform a test `F_PUNCHHOLE` of length 0 …

Support TRIM on raw files via F_PUNCHHOLE

---

Makefile
src/hyperkit.c
src/include/xhyve/firmware/bootrom.h
src/include/xhyve/fwctl.h
src/lib/firmware/bootrom.c
src/lib/fwctl.c

This enables the UEFI firmware to correctly detect the number of vcpus. Without this the guest only sees 1 vcpu regardless of the use of `-c` because the firmware tables (ACPI) won't be setup correctly.
The first commit simply imports the pristine files from FreeBSD, the second commit is the interesting one I guess.

Port fwctl over from bhyve

---

go/hyperkit.go

A bunch of minor stylistic changes, and a new feature, needed to allow Docker 4 Mac to rely on this hyperkit.go to launch hyperkit.

Go: support exec.Cmd's extra files

---

go/hyperkit.go

In Docker for Mac, this is used so that all the processes belong to the `com.docker.*` family.

go: provide a means to change argv[0]

---

dtrace/block-trace.d
dtrace/eptfault.d
dtrace/vmxexit.d

- Run with `cpp` to make them work at all
- Workaround corrupted output issues (looks like a `dtrace` bug)
- Add optional periodic output when tracing
- Add a simple script to trace block device activity

dtrace fixes and improvements

---

README.md

Initially, I only wanted to see build badge, but then I also fixed the links for {vpn,data}kit.

Fix repo references in README.md

---

go/Makefile
go/disk.go
go/disk_test.go
go/hyperkit.go
go/log.go
go/pty_util_fallback.go
go/sample/main.go

This is the changes that are currently running in Docker for Mac.  I have removed the stylistic issues (adjusted comments, scope reduction, etc.) that were discussed in https://github.com/moby/hyperkit/pull/167.  The `defaultString` function is removed at the end.
Cheers!

Changes for Docker for Mac

---

go/hyperkit.go
go/sample/main.go

Currently we offer two means to run hyperkit: `Start` and `Run`. Both run the process in background (using `exec.Cmd.Start`), in order to be able to save the state when launching succeeded.
Both wait for the command to finish.  `Run` returns the exit status. `Start` waits in a goroutine and discard the result.
As a result, the user has no clean means to run in background and get the exit status.  The `Start` function discards the exit status.  But since `Run` is blocking, the caller must run it in a goroutine.  Therefore the callers needs to watch the process to know when it is actually running (e.g., by watching `h.Pid`).
Revamp this.
- First, make changes easier by isolating the checking and the `exec.Cmd` creation parts into their own functions
- Provide the HyperKit struct with a …

Go: revamp the Start/Run procedures

---

go/disk.go

I would like to compare the disk's required size with the current size to eventually remove the disk image before calling `Ensure()` (when desired smaller than current). I just need `getCurrentSize` to be made public.

go: make Disk.getCurrentSize() public

---

go/hyperkit.go

It was introduced for Docker for Mac in d1a5c32a404a86facc5800d962901b5e7a1783d9, so that we could ensure that Docker for Mac's lockfile would be preserved even if it were to crash. This use was removed in 2bedc1969f8c6893678fdef55e90e734c170c42c since djs55 had qcow-tool deal with the lock itself.

Go: remove the ExtraFiles field

---

go/disk.go
go/log.go

These logs are currently emitted by Docker for Mac, but I believe they make more sense here.

Go: add logs about qcow compaction and runtime checks

---

go/hyperkit.go
go/sample/main.go

In https://github.com/moby/hyperkit/pull/174#issuecomment-356305949 it was discussed that this feature might be unused and useless.   This PR is meant to sort this out.

Go: remove the reloading from json

---

go/disk.go

APFS exhibits a weird behavior wrt sparse files: we cannot create (or grow) them "too fast": there's a limit, apparently related to the available disk space.  However, if the additional space is small enough, we can procede way beyond the available disk space.  So grow incrementally, by steps of 1GB. 
More details available in https://github.com/docker/for-mac/issues/2383.

Grow disk more slowly, workaround ENOSPC from ftruncate

---

Makefile
circle.yml

So that when we download an artifact we can relate it to a precise commit.

CI: also publish the COMMIT

---

go/disk.go
go/hyperkit.go

- Remove per hyperkit instance SetLogger(). It's not per instance
- Add '.img' as a recognised raw disk extension

Minor tweaks to go bindings

---

go/disk.go
go/hyperkit.go
go/pty_util_fallback.go

- remove useless code
- simplify log redirection
- make sure all the logs are reported as `hyperkit:`
Instead of log redirection for hyperkit(.exe) it would be much more convenient for Docker for Mac that hyperkit used aslog directly, so that its logs are properly credited to it rather than to the caller, which happens to be com.docker.driver.
cc: @djs55

Simplify logs

---

.circleci/config.yml

It looks like perhaps some sort of upgrade rename around Python/Python 3 has
gone on so I'm hoping this might help.
Deliberately not signed off (yet) because I think our bot is broken and I want to
test that too.

Manually upgrade Python to avoid brew failures

---

test/tinycore.sh

ibiblio is giving 404.
Signed-off-by: Ian Campbell <ijc@docker.com>

ci: switch to main tinycorelinux mirror

---

CODINGSTYLE.md
Makefile
go/hyperkit.go
src/include/xhyve/log.h
src/lib/log.c
src/lib/uart_emul.c

This is https://github.com/moby/hyperkit/pull/196 rewritten with comments from @rn and @ijc integrated.
On Docker for Windows, all the logs are aggregated: GUI, LinuxKit, etc.  Currently debugging on Docker for Mac is less easy, in particular because LinuxKit's log are sent to the consolefile rings of fixed sized buffers.  As a result, it's hard to find the interleaving of actions between Docker for Mac and LinuxKit, the console files are fragmented and full of '\0', etc.
It is possible to have hyperkit redirect the tty's output to its stderr/stdout, and then its caller (Docker for Mac's driver) could redirect these streams to the logger.  Unfortunately on recent macOS releases, asl is replaced by os_log which uses exclusively the path of the executable as source (changing `argv[0]` is …

Offer a means to send the tty to the Apple log system

---

src/lib/firmware/bootrom.c

resolved formatter type error

---

go/hyperkit.go

hyperkit happily boots with just a kernel (and the rootfs on
a disk device, for example). So, if booting in non-fw mode
only check for the kernel.

go: Don't check for initrd

---

.circleci/config.yml

Also revert the Python workaround from f55b5442ad65188f0002264a08de38ca47350e4d
which was added in #202.
Signed-off-by: Ian Campbell <ijc@docker.com>
The removal of the Python workaround is optimistic/speculative in case this base image has a newer brew than the old one, if that turns out not to be the case I'll drop that hunk and continue to rely on #203.

ci: bump to xcode 9.3 and minimum MacOS to 10.11

---

src/lib/pci_ahci.c

This is a manual "cherry-pick" of FreeBSD bhyve commits:
- 9b141cb38697 ("Add Log directory and SATA NCQ Send and Receive Log.")
- 6f295d26ad99 ("Fix variable for sizeof() in previous commit.")
The main original commit message is:
commit 9b141cb386977064a49f9d035e7dee35b6b4d5d5
Author: mav <mav@FreeBSD.org>
Date:   Sun Apr 2 20:39:51 2017 +0000
Add Log directory and SATA NCQ Send and Receive Log.
Those are used at least by Linux guests to detect queued TRIM support.
MFC after:      2 weeks
Sponsored by:   iXsystems, Inc.
I've ran a few kernel compiles and other relatively disk intensive loads through it and it was holding up.

Add Log directory and SATA NCQ Send and Receive Log.

---

src/include/xhyve/block_if.h
src/lib/block_if.c
src/lib/pci_ahci.c
src/lib/pci_virtio_block.c

Commit 6e72b75 ("Lock the backing file to prevent concurrent
modification") added locking to block device backing files. It
uses a shared lock for read-only devices (',ro' option) and an
exclusive lock by default.
The ahci-cd device only supports read-only ISOs as backing file
so it is cumbersome having to specify ',ro' as option in order
to share the same ISO between different HyperKit instances.
This commit adds a 'ro' argument to 'blockif_open()' and only
sets it for ahci-cd devices. This then causes the ISO backing
file to opened with 'O_RDONLY' and a shared lock being taken.
There should be no change for other block devices.

Open ISO images (ahci-cd backing files) as read-only

---

src/lib/vmm/intel/vmx.c

hv_vm_create may fail with
- HV_BAD_ARGUMENT
- HV_BUSY
- HV_NO_DEVICE
- HV_NO_RESOURCES
- HV_UNSUPPORTED
While we already handled `HV_NO_DEVICE` carefully, for the rest we would abort with `hv_vm_create failed` which isn't very helpful. This patch adds a `printf` of the error code so we can investigate a little more (see for example [docker/for-mac#3015])

Log the error if hv_vm_create fails

---

src/lib/mirage_block_ocaml.ml

In newer versions of OCaml (4.06 and later) `-safe-string` is on by default which means there is a difference between the `string` and `bytes` types where `string` is immutable but `bytes` is mutable.
The expression `Bytes.unsafe_of_string "X"` returns a mutable reference to the constant buffer "X" but the `Unix.write` call will not write to it.

ocaml: be compatible with -safe-string

---

.circleci/config.yml

The current homebrew default is opam 2. We should upgrade to opam 2
but this temporary workaround will unblock other PRs.

ocaml: install opam 1 explicitly

---

src/lib/vmm/intel/vmx.c

["cherry picked" from https://github.com/machyve/xhyve/commit/cc672d5363766e7c2bf10e02ca12efbeda74c487]
Recent Linux kernels (late 4.17) disable paging temporarily
when in long-mode. Handle this case by updating guest and VM
state to make sure they are in sync: EFER.LMA is cleared,
and the 'IA-32e mode guest' entry control is set to 0.
This is effectively the reverse operation to the existing case
when CR0.PG is set.
Signed-off-by: Rolf Neugebauer <rn@rneugeba.io>
Thanks to @grehan-freebsd for the pointer. This lets me boot a 4.19.7 kernel without issue.
resolves #226

Fix invalid-guest-state entry by updating state when CR0.PG cleared.

---

README.md

Docker for Mac has been renamed Docker Desktop for Mac.
See https://docs.docker.com/docker-for-mac/install/

README: Rename Docker for Mac -> Docker Desktop for Mac

---

README.md

trying to install qcow.0.10.3 yields a dependency problem:
> The following dependencies couldn't be met:
>   - qcow-tool → qcow >= 0.10.4
>   - qcow-tool → sha = 1.9 → ocaml < 4.06.0
>       base of this switch (use `--unlock-base' to force)
> Your request can't be satisfied:
>   - No available version of qcow satisfies the constraints
> 
> No solution found, exiting
But qcow.0.10.4 works

README update: opam install qcow.0.10.4

---

.circleci/config.yml
go/Makefile

The current one gives the following error:
Error: opam: "cxx11" is not a recognized standard
I cargo culted this change from https://github.com/moby/vpnkit/commit/4bb313b0d76fccc508299133e36c2c015184eec8
Signed-off-by: Ian Campbell <ijc@docker.com>

circleci: use a patched opam.rb

---

src/include/xhyve/firmware/fbsd.h
src/lib/firmware/fbsd.c

This change pulls in the update made by jeremyhu in the upstream xhyve project with commit 9ea6650d3766c897ef85a3df15fdd9abcc9ee858 and resolves all implicit conversion errors reported in MacOS Mojave 10.14.4 with LLVM 10.0.1, as reported in issue #246

Resolve implicit conversion error on latest MacOS Mojave with latest Xcode

---

go/hyperkit.go

Fixes https://github.com/moby/hyperkit/issues/253

Fixed auto location of vpnkit socket

---

.circleci/config.yml

This works around a brew autoupdate bug following advice from
https://discuss.circleci.com/t/brew-install-fails-while-updating/32992/3

circleci: install opam 1 (fixes the CI)

---

.circleci/config.yml
config.mk
repo/opam-licenses.sh
src/include/xhyve/vmm/vmm.h
src/include/xhyve/vmm/vmm_api.h
src/include/xhyve/vmm/vmm_common.h
src/lib/mirage_block_ocaml.ml
src/lib/pci_virtio_sock.c
src/lib/task_switch.c
src/lib/vmm/intel/vmx.c
src/lib/vmm/vmm.c
src/lib/vmm/vmm_api.c
test/test_linux.exp
test/test_linux_qcow.exp

This is an experiment similar to #261 and #266.
Rather than cast everything to `(int)` I've tried to plumb though the type `enum vm_reg_name` and only cast to `(int)` at the lower level.

Another attempt to fix signedness warnings

---

go/disk.go
go/disk_test.go
src/lib/pci_virtio_block.c

The protocol defines DISCARD in v1.1:
https://docs.oasis-open.org/virtio/virtio/v1.1/cs01/virtio-v1.1-cs01.pdf
In this simple implementation we advertise a maximum of 1 segment per request, which fits the backend API `block_delete(_, offset, length)`. Experimentally Linux 5.4.9 seems to send one request at a time (tested by deleting files and then executing `fstrim`)
Note we only advertise the feature if the backing file itself supports it.
Switching from AHCI `virtio-blk` works around the known deadlock in the AHCI implementation #94

virtio-blk: implement DISCARD

---

Makefile
test/retry-infra-failure
test/test_linux.exp
test/test_linux_qcow.exp
test/tinycore.sh

The CircleCI nested virtualisation often fails with
```
Kernel panic - not syncing: IO-APIC + timer doesn't work!  Boot with apic=debug and send a report.  Then try booting with the 'noapic' option.
```
Let's try booting the test kernels with the `noapic` option.

test: attempt to make CI more robust

---

README.md

This is a trivial patch designed to trigger the CI since I don't have access to CircleCI to press the rebuild button.

README.md: it should be "for Mac" not "For Mac"

---

src/lib/block_if.c

Previously we didn't log which device doesn't support TRIM. On systems where some disks support TRIM and some don't it's helpful to know which is which.
Previously we would log that it is the host filesystem which doesn't support TRIM. This isn't always the reason -- for example the file could be open read-only, causing our test TRIM to fail.
This patch includes the filename in the log message and simply says that TRIM/DISCARD won't be supported e.g.
```
docker-desktop.iso: fcntl(F_PUNCHHOLE) Operation not permitted: block device will not support TRIM/DISCARD
```

Improve error message if TRIM/DISCARD isn't supported

---

src/lib/pci_virtio_net_vmnet.c

Use the MAC address from PCI configuration (if provided) as documented in the man page.
HyperKit cmd:
```
build/hyperkit -A -u -U f9012ed3-3f13-4a5c-a2f4-f5af25d4826c -c 1 -m 1G -H -P -l com1,stdio -s 0,hostbridge -s 1,lpc -s 2,virtio-rnd -s 3,virtio-net,,mac=fC:72:d0:92:cb:0f -f kexec,boot2docker/vmlinuz,boot2docker/initrd.img,earlyprintk=serial console=ttyS0
```
Result of `ifconfig` on the vm:
```
docker@boot2docker:~$ ifconfig
docker0   Link encap:Ethernet  HWaddr 02:42:A2:97:FE:69
inet addr:172.17.0.1  Bcast:172.17.255.255  Mask:255.255.0.0
UP BROADCAST MULTICAST  MTU:1500  Metric:1
RX packets:0 errors:0 dropped:0 overruns:0 frame:0
TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
collisions:0 txqueuelen:0
RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
eth0      Link encap:Ethernet …
```

virtio-net: use mac address from pci configuration

---

src/lib/vmm/intel/vmx.c
src/lib/vmm/intel/vmx_msr.c

There have been some observed initialisation failures on new hypervisors / hardware, caused by us not recognising a new hypervisor feature. Previously the code would print an error and exit if it encountered an unknown feature.
However the hypervisor is able to provide a safe default, so we should use that instead. Setting the features we want is a VMCS write and querying the default fields is a VMCS read.
Therefore this patch
- moves the capability probing into the vCPU setup where a VMCS read is possible
- initialises the feature bits with a VMCS read (previously these were all 0)
- removes the failure case when we encounter an unknown feature bit (since the default will be safe)

vmx: inherit defaults from hypervisor

---

src/lib/pci_virtio_net_vmnet.c

When using virtio-net with an UEFI firmware (-f bootrom),
hyperkit crashes on an assertion. See the related bug on
xhyve: https://github.com/machyve/xhyve/issues/164
The complete details are not clear to me, but it seems
that during boot, the firmware reads on the interface but
doesn't provide big enough read buffers. It seems that
the space for VLAN headers is missing.
This patch drops the related reads, so normal booting can
occur. Network boot probably doesn't work, though.
Signed-off-by: Antoine Martin <amartin@unowhy.com>

fix: Fix upstream xhyve crash (virtio-net + UEFI)

---

src/lib/uart_emul.c

If the osquery tool[1] is running and scanning a directory containing the `tty` symlink, it will follow the link to `/dev/ttys*` and start some kind of infinite loop involving the debug console. This causes hyperkit's CPU to spike and for the console itself to be spammed with it's own output.
The easiest workaround is to not create the symlink, but write the name of the tty in a file instead. Therefore for debugging we can still run
```
screen $(cat ~/Library/Containers/com.docker.docker/Data/vms/0/tty)
```
(or equivalent)
Reported originally around here[2]
[1] https://osquery.io/downloads/
[2] https://github.com/docker/for-mac/issues/3499#issuecomment-639140844

tty: write filename in a file, don't symlink to /dev

---

src/lib/uart_emul.c

After installing 2.3.3.0 I was unable to run `cat ~/Library/Containers/com.docker.docker/Data/vms/0/tty` because file permissions were 000. It looks like open() in 4aad16e4e with O_CREAT flag takes three arguments, but only two were provided and that third argument was taken from stack, which resulted in zero permissions on file in my case.

fix tty file permissions

---

go.mod
go.sum
go/hyperkit.go
go/hyperkit_test.go
src/lib/uart_emul.c

The current Go API for setting up the serial console has limitations, including:
- it supports at most one serial port
- it requires either `stdio` or a `tty`, and will trigger an `assert` if you don't provide one of them
- it combines the request for a `tty` with the request to log the output to a ring-buffer or to Apple System Log.
This PR adds a new Go API while keeping (but deprecating) the old one. It's now possible to have multiple serial ports, each of which is connected to one of:
- `/dev/null`
- a TTY
- `stdio`
and of which can be separately logged to any combination of:
- `/dev/null`
- a ring buffer
- Apple System Log
This PR also adds a `go.mod` and some unit tests for the console-related command-line building functions.

go: improve serial console

---

go.mod
go.sum
go/pty_util_darwin.go

This is necessary due to an upgrade in Golang's sys package, which no longer allows for direct system calls on darwin.
Fixes https://github.com/moby/hyperkit/issues/298
This code was copied from https://github.com/containerd/console/blob/2f74731477a5334b870605b261bcfb71ba34c56a/tc_unix.go, which a comment at the top of the file says the old code came from.

Use unix.IoctlSetTermios instead of ioctl system call on darwin

---

Makefile
app.entitlements
config.mk

On Bigsur need to add Hypervisor framework entitlement.
Based on https://stackoverflow.com/questions/64642062/apple-hypervisor-is-completely-broken-on-macos-big-sur-beta-11-0-1
via https://github.com/moby/hyperkit/issues/300#issuecomment-747457675
Signed-off-by: Rolf Neugebauer <rn@rneugeba.io>
fixes #300

build: Add entitlements

---

src/lib/firmware/multiboot.c

Hyperkit's multiboot loader incorrectly loads the firmware into guest memory.
This patch fixes the offset used to load the firmware image by using the offset of the first (smallest offset) loaded program segment in an elf32 firmware.
In essence what was happening before this patch was that hyperkit would load the entire ELF32 binary into memory from the start of the image. In some cases this works due to how some firmware image are built, but the correct behavior I think should be to find the offset instead of having to apply some link time tricks.

Fix for multiboot loader

---

.gitignore
Info.plist.in
Makefile

When hyperkit is bundled and deployed widely, this makes it easier to
associate policy or patches directly with it. It shouldn't have any
other effect.
It's possible to view the embedded Info.plist with
```
% otool -s __TEXT __info_plist ./build/hyperkit | xxd -r
```

Embed an Info.plist, with a distinct bundle identifier

---

src/lib/pci_virtio_rnd.c
src/lib/pci_virtio_sock.c
src/lib/virtio.c

This series add some fixes for various cases that have been reported that allow the guest to trigger a crash of the virtual machine.
The first two are NULL pointer dereference and are already handled in bhyve.
https://cgit.freebsd.org/src/tree/usr.sbin/bhyve/virtio.c#n606
https://cgit.freebsd.org/src/tree/usr.sbin/bhyve/virtio.c#n725
The other two are unhandled returned errors in vq_getchain. For now, trace and return as in pci_vt9p_notify.
Let me know what you think.

Various fixes

---

Makefile
src/lib/pci_virtio_block.c

The assertion is supposed to check the value, but the typo makes it
an assignment. Hence it is always true.
Fixes GHSL-2021-058

Fix assertion turned into assignment

---

Makefile

Fixes the recent CI error. Caused by stubs moving from one .a to another in an upstream dependency.
I think the combination of #304 and this should fix #301.
Fixes CI failure seen in #318
It would be nice to have a better set of Makefile rules for finding these C stubs.

Include _caml_mirage_iopage_{alloc_pages,get_addr}

---

LICENSE
README.md

This makes it easier for license gathering tools to automatically find the license type and text. Moreover GitHub has API endpoints to query this: see https://docs.github.com/rest/reference/licenses#get-the-license-for-a-repository.
Closes #327

Move license text to dedicated file
