README.md

Add CI status to README.md

---

src/pci_virtio_sock.c

Commit a966247ad850 ("vsock: Add socks which require a credit update to the
rx_queue") ensured that sockets which required a credit update were included in
the rx queue even if they had no rx activity to process, however since they are
not included in the set of select()d fds the thread can block waiting for
activity on one of the other threads rather than processing the pending update.
If there are such pending updates then pass a zero timeout to select, this will
poll the status of all the active fds (so we will process what work exists),
but not block so we will immediately process the credit updates too.
If we are not polling sockets at all (poll_socks = false) then we are waiting
for more descriptors and couldn't send a credit update, so don't do anything
with socks requiring a …

vsock: don't block rx in select if there are pending credit updates

---

MAINTAINERS
README.md

Signed-off-by: Anil Madhavapeddy <anil@recoil.org>

consistently spell the project: s/Hyperkit/HyperKit/g

---

src/pci_virtio_sock.c

Retry when appropriate and log the failure reason for other failures.

Improve logging/debugging when select() fails

---

src/pci_virtio_sock.c

This adds a possible fix for docker/for-mac#104 as well as some comments which I hope will make the current situation WRT the checks for reply_ring fullness (mentioned on #50) somewhat clearer.

vsock backend updates

---

src/pci_virtio_sock.c

The `assert` and the` _rx` suffix on the function are wrong, it is perfectly
fine to call from either rx or tx thread.
In principle it would be possible to have an optimised tx-thread-only version
which could skip the CLOSING_TX state and go right to CLOSING_RX, the current
state prior to this commit is a botched/incomplete attempt at such an
optimisation (but the wrong way round and broken).

Fix local shutdown

---

CODINGSTYLE.md

docs: Add coding style *guidelines*

---

src/lib/pci_virtio_sock.c

pci_vtsock_rx_thread() assumes that if pci_vtsock_proc_rx() returned >= 0 then
something will have been queued on the ring and therefore a credit update is no
longer required (credit updates can piggy back on any traffic).
However there were two paths through pci_vtsock_proc_rx() which did not send
anything:
- The peer has no buffer space available (when peer_buf_alloc - (rx_cnt -
peer_fwd_cnt) == 0).
- Read on the Unix domain socket returned EAGAIN (nothing to read).
This would result in rx_thread() clearing s->credit_update_required when the
update was still required, which could lead to a deadlock for that socket if
there happened to be no other pending tx traffic to generate a second attempt
at a credit update.
Fix this by:
- moving the clearing of the flag to exactly the place which …

vsock: do not clear s->credit_update_required if no traffic sent

---

README.md

these code blocks in README did not work the right way, I just fixed them

fixed README's code blocks

---

src/lib/pci_virtio_sock.c

Various issues found by running hvgostress from https://github.com/rneugeba/virtsock and from investigations of https://github.com/docker/for-mac/issues/825 (although sadly even these do not fix that issue).

Vsock locking fixes

---

src/lib/mirage_block_ocaml.ml

The Mirage I/O operations are supposed to return a result type as follows:
[ `Ok of result | `Error of error description ]
If the implementation actually fails i.e. by raising an exception, this would
propagate and prevent the client request ever returning. This patch catches
stray exceptions, logs something about them, and returns an error to the
caller.

ocaml: if a Mirage thread fails, ensure we fail the request

---

README.md
circle.yml

From hyperkit's point of view, the qcow changes are:
- fix a major performance problem with online GC/compact which could manifest as an I/O timeout, triggering an AHCI reset and then deadlock
- gather performance counters in a format suitable for prometheus (although there is no code to expose them anywhere yet)
https://github.com/mirage/ocaml-qcow/blob/master/CHANGES.md

qcow: update to v0.10.0

---

MAINTAINERS

Update Rolf Neugebauer's and my own github ids

---

go/hyperkit.go
go/sample/main.go

Changes DiskImage to an array called DiskImages with keys Path and
SizeMB. Also changes the JSON key from "disk" to "disk_images".
DiskSize is removed as size is set per disk image.
This allows multiple block devices to be mounted via the API and fixes #137

go API: Add support for more than one block device

---

go/hyperkit.go

This can be used for UEFI boot for example.
Signed-off-by: Justin Cormack <justin.cormack@docker.com>

Add support for setting a bootrom in Go API

---

go/hyperkit.go

- define a Logger interface to gain independance.
- really use the user's logger
If preferred, I can split this in three steps.

go: don't tie the users to golang's log

---

go/hyperkit.go

This is needed to support qcow2 disks given that
file uris seem to be required.
When using a qcow2 disk with a non-uri path you'll get
the error
"Config.to_string expected a string of the form file://<path>?sync=(none|os|drive)&buffered=(0|1)"
Signed-off-by: dave <dprotaso@gmail.com>

File URIs are now valid inputs for DiskConfig paths

---

go/disk.go

This is now handled by qcow-tool itself for `compact`.  It was actually not needed for `check`: it is read-only and designed to work on a live disk.
See https://github.com/mirage/ocaml-qcow/pull/106.

Go: remove uses of the lock file

---

go/disk_test.go

go: Fix disk test

---

src/lib/block_if.c

We present a virtual sector size of 512 to the VM but are likely using
a 4096 byte native sector size on the local SSD, therefore we have to
take care to align calls to `fcntl(F_PUNCHHOLE)`.
Previously we would align up the `fp_offset` to the native sector size
and then compute the length of the unaligned initial region we need
to manually zero by `aligned_offset - fp_offset`. Unfortunately this
fails to take into account that the `fp_length` might be smaller than
this, for example:
assume `fp_offset = 1024` and `fp_length = 512` (i.e. TRIM one sector)
=> `aligned_offset = 4096`
=> `len_to_zero = aligned_offset - fp_offset = 3072`
and we will erase `3072` bytes even though the request was for `512`.
We will then go on to calculate a -ve number for the `fcntl(F_PUNCHHOLE)`
call which will …

Fix TRIM/DISCARD of small regions

---

README.md

Signed-off-by: James Hill-Khurana <hello@jameshk.com>

Change references of OS X to macOS

---

hyperkit.1
src/hyperkit.c
src/include/xhyve/xhyve.h
src/lib/pci_virtio_net_vmnet.c

Signed-off-by: Noel Georgi <git@frezbo.com>
Fixes: #236 @ijc

Pulling changes from xhyve

---

src/lib/pci_emul.c

Avoid null pointer dereference in pci_bus_write_dsdt

---

src/lib/pci_virtio_9p.c
src/lib/pci_virtio_sock.c

Already approved by @rn out of band.

Fix various overflow issues

---

MAINTAINERS

Add ebriney to MAINTAINERS
